Decentralicense 1.0
rainlanguage/decentralicense pull request #1
Opened 2024-04-11 06:14 UTC by pjbrow

2024-04-11 11:29 UTC, thedavidmeister requested changes

2024-04-11 11:29 UTC, thedavidmeister commented on README.md
> +### 4.3. Maintain Private Key Exclusive Control
4.3 here twice

2024-04-11 20:24 UTC, pjbrow commented on README.md
> +### 4.3. Maintain Private Key Exclusive Control
@thedavidmeister Fix applied.

2024-04-11 20:28 UTC, merged

2024-08-23 04:04 UTC, nand16041987 reviewed
G